### ISSUE TITLE
Error: yarn global add mirror-config-china

### ISSUE THREAD

**Issue by meteorlxy** [gucong3000/mirror-config-china#42]
Run command:
```
yarn global add mirror-config-china
```

Error Stack:
```
error C:\Users\***\AppData\Local\Yarn\Data\global\node_modules\mirror-config-china: Command failed.
Exit code: 1
Command: node lib/install
Arguments:
Directory: C:\Users\***\AppData\Local\Yarn\Data\global\node_modules\mirror-config-china
Output:
TypeError: path must be a string or Buffer
    at fs.readFile (fs.js:358:11)
    at go$readFile (C:\Users\***\AppData\Local\Yarn\Data\global\node_modules\graceful-fs\graceful-fs.js:73:14)
    at Object.readFile (C:\Users\***\AppData\Local\Yarn\Data\global\node_modules\graceful-fs\graceful-fs.js:70:12)
    at Promise (C:\Users\***\AppData\Local\Yarn\Data\global\node_modules\universalify\index.js:13:12)
    at new Promise (<anonymous>)
    at Object.readFile (C:\Users\***\AppData\Local\Yarn\Data\global\node_modules\universalify\index.js:7:14)
    at setConf (C:\Users\***\AppData\Local\Yarn\Data\global\node_modules\mirror-config-china\lib\npmrc.js:9:12)
    at Object.<anonymous> (C:\Users\***\AppData\Local\Yarn\Data\global\node_modules\mirror-config-china\lib\install.js:12:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**Comment by gucong3000** [comment]
fixed in `mirror-config-china@2.5.1`
